tabs:
    fields:
        logo:
            label: logo
            type: fileupload
            commentAbove: logo_description
            mode: image
            tab: general
            span: auto
            fileTypes: jpg,jpeg,bmp,png,webp,gif,svg
        favicon:
            label: favicon
            type: fileupload
            commentAbove: comment
            mode: image
            imageHeight: 32
            tab: general
            span: auto
            fileTypes: jpg,jpeg,bmp,png,webp,gif,svg,ico

